### ISSUE TITLE
[Crash]: GS crashes OpenTTD with malformed comment prefix

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#10361]
### Version of OpenTTD

750d89d37b372b808e616091913f7e48f6d4d0ea but rev is probably not significant

### Steps to reproduce

Use a python-style comment by mistake in a GS/squirrel .nut file.

E.g. 

`# foo`

instead of

`// foo`

### Upload crash files

```
[2023-01-15 23:34:24] dbg: [script] [18] [S] Error /Users/cabbage/Documents/OpenTTD/game/firs-gs/temp_prototyping.nut:59/10: expression expected
[2023-01-15 23:34:24] dbg: [misc] [squirrel] Failed to compile '/Users/cabbage/Documents/OpenTTD/game/firs-gs/temp_prototyping.nut'
[2023-01-15 23:34:24] dbg: [script] [18] [S] Your script made an error: expression expected
[2023-01-15 23:34:24] dbg: [script] [18] [S] 
[2023-01-15 23:34:24] dbg: [script] [18] [S] *FUNCTION [main()] /Users/cabbage/Documents/OpenTTD/game/firs-gs/main.nut line [55]
[2023-01-15 23:34:24] dbg: [script] [18] [S] 
[2023-01-15 23:34:24] dbg: [script] [18] [S] [this] TABLE
[2023-01-15 23:34:24] dbg: [misc] [squirrel] Failed to compile '/Users/cabbage/Documents/OpenTTD/game/firs-gs/main.nut'
[2023-01-15 23:34:24] dbg: [script] The script died unexpectedly.
Crash encountered, generating crash log...
*** OpenTTD Crash Report ***

Crash at: 2023-01-15 23:34:24 (UTC)
In game date: 1900-10-13 (45)

Crash reason:
 Signal:  Segmentation fault: 11 (11)
 Message: <none>

OpenTTD version:
 Version:    20230115-master-m96ec9908a0 (2)
 NewGRF ver: 1e006d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Jan 15 2023 15:12:49


Stacktrace:
 [00] openttd              0x00000001006bf16c (CrashLog::FillCrashLog(char*, char const*) const + 368)
 [01] openttd              0x0000000100598558 (CrashLogOSX::MakeCrashLog() + 100)
 [02] openttd              0x0000000100598448 (HandleCrash(int) + 276)
 [03] libsystem_platform.dylib 0x00000001a86434a4 (_sigtramp + 56)
 [04] openttd              0xba798001003b29c4 (Game::StartNew() + -5009832372984610448)
 [05] openttd              0x00000001003b29c4 (Game::StartNew() + 368)
 [06] openttd              0x00000001005d5a44 (AfterLoadGame() + 54380)
 [07] openttd              0x0000000100611ffc (DoLoad(LoadFilter*, bool) + 3348)
 [08] openttd              0x0000000100612884 (SaveOrLoad(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, SaveLoadOperation, DetailedFileType, Subdirectory, bool) + 1404)
 [09] openttd              0x000000010081b064 (SafeLoad(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, SaveLoadOperation, DetailedFileType, GameMode, Subdirectory, LoadFilter*) + 212)
 [10] openttd              0x000000010081b86c (SwitchToMode(SwitchMode) + 1468)
 [11] openttd              0x000000010081f62c (GameLoop() + 472)
 [12] openttd              0x0000000100655e8c (VideoDriver::GameLoop() + 116)
 [13] openttd              0x00000001006560ac (VideoDriver::GameThreadThunk(VideoDriver*) + 80)
 [14] openttd              0x0000000100656984 (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, bool StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::__1::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::'lambda'(char const*, void (*&&)(VideoDriver*), VideoDriver*&&), char const*, void (*)(VideoDriver*), VideoDriver*> >(void*) + 84)
 [15] libsystem_pthread.dylib 0x00000001a862c26c (_pthread_start + 148)
 [16] libsystem_pthread.dylib 0x885e8001a862708c (thread_start + -8620311899252195320)

Operating system:
 Name:     Mac OS X
 Release:  12.6.2
 Machine:  ARM64E
 Min Ver:  101300
 Max Ver:  130100
 Compiler: GCC 4.2.1 "Apple LLVM 14.0.0 (clang-1400.0.29.202)"

Configuration:
 Blitter:      40bpp-anim
 Graphics set: original_windows (0)
 Language:     /Users/cabbage/stuff/build/lang/english.lng
 Music driver: cocoa
 Music set:    original_windows (1)
 Network:      no
 Sound driver: cocoa
 Sound set:    original_windows (0)
 Video driver: cocoa-opengl (Apple M1 Pro, 4.1 Metal - 76.3)

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

AI Configuration (local: 0) (current: 18):
  0: Human
 GS: FIRS GS (v1)

Libraries:
 LZMA:       5.0.5
 LZO:        2.10
 PNG:        1.6.39
 Zlib:       1.2.11

---- gamelog start ----
Tick 0: new game started
Revision text changed to m96ec9908a051f, savegame version 302, modified, _openttd_newgrf_version = 0x1e006d64
New game mode: 1 landscape: 0
Added NewGRF: GRF ID 43415000, checksum FBAE0C1ACFDA5AE8B95B4DA230A395FE, filename: opengfx_airports-0.5.0/ogfx-airports.grf (md5sum matches)
Added NewGRF: GRF ID 9787EAFE, checksum 04ACD20A006E345283D6464678AFFA8B, filename: road_hog-1.4.1/road-hog.grf (md5sum matches)
Added NewGRF: GRF ID 44440A80, checksum 2F7F4BC7FBAD4544CA241DFE6D5A6F39, filename: av9.8-0.97/av9point8.grf (md5sum matches)
Added NewGRF: GRF ID FBFB9905, checksum F747797A14AAA646402DC4E16DE5E82C, filename: longer_girder__steel_bridge.1/longergirdersteelbridge.grf (md5sum matches)
Added NewGRF: GRF ID 55535333, checksum 7648EE94EC567D8931F691AAA5BCF912, filename: unsinkable-sam.grf (md5sum matches)
Added NewGRF: GRF ID 43485054, checksum F09180381B487C911D5EAF5DFF4FDDF2, filename: chips_station_set_2-2.0.0/chips.grf (md5sum matches)
Added NewGRF: GRF ID 54540301, checksum F7CDD4F730E4F3EE87100CE42E5070AE, filename: itl_houses-2.1/itl_houses.grf (md5sum matches)
Added NewGRF: GRF ID F1250008, checksum 1C665399A6ED1E6DD57D53D6FBB17DA1, filename: firs-crustywell-game.grf (matches GRFID only)
Added NewGRF: GRF ID 43411222, checksum 7E62085010B3FB43CAA1F9116655405E, filename: iron-horse.grf (md5sum matches)
Tick 14816: GRF config changed
Added NewGRF: GRF ID 41501202, checksum B13DD8FB0D7C34CACAC2FE68BD137BB9, filename: heqs_heavy_equipment_set-1.5.2/heqs.grf (md5sum matches)
Tick 24462: game loaded
New game mode: 2 landscape: 0
Tick 24462: game loaded
New game mode: 1 landscape: 0
Tick 27309: game loaded
New game mode: 2 landscape: 0
Compatible NewGRF loaded: GRF ID F1250008, checksum 3CCB099044174030418F5072010454C3, filename: firs-crustywell-game.grf (matches GRFID only)
Tick 27309: game loaded
New game mode: 1 landscape: 0
Tick 48444: game loaded
Compatible NewGRF loaded: GRF ID F1250008, checksum 31DDF2236B86CCA6735E56F590C29202, filename: firs.grf (md5sum matches)
---- gamelog end ----

Recent news messages:

*** End of OpenTTD Crash Report ***

Crash log generated.

Writing crash log to disk...
Writing crash savegame...
Writing crash screenshot...
[2023-01-15 23:34:24] dbg: [misc] /Users/cabbage/stuff/src/game/game_core.cpp:88: Backed-up value was not restored!
[2023-01-15 23:34:24] dbg: [sl] Game Save Failed
(undefined string)
^C
```

**Comment by glx22** [comment]
Please attach the GS, I tested with `# foo` in 2 different locations and it didn't crash for me.

```
[2023-01-16 01:07:43] dbg: [script] [18] [S] Error D:\Mes documents\OpenTTD\game\test\main.nut:4/3: expected 'IDENTIFIER'
[2023-01-16 01:07:43] dbg: [misc] [squirrel] Failed to compile 'D:\Mes documents\OpenTTD\game\test\main.nut'
[2023-01-16 01:07:43] dbg: [script] The script died unexpectedly.
```
```
[2023-01-16 01:11:02] dbg: [script] [18] [S] Error D:\Mes documents\OpenTTD\game\test\main.nut:6/3: expression expected
[2023-01-16 01:11:02] dbg: [misc] [squirrel] Failed to compile 'D:\Mes documents\OpenTTD\game\test\main.nut'
[2023-01-16 01:11:02] dbg: [script] The script died unexpectedly.
```

**Comment by TrueBrain** [comment]
And can you confirm this also crashes with a nightly? Just to rule out it is not because of your custom binary? Tnx!

**Comment by andythenorth** [comment]
[gs.zip](https://github.com/OpenTTD/OpenTTD/files/10439736/gs.zip)

**Comment by andythenorth** [comment]
> And can you confirm this also crashes with a nightly? Just to rule out it is not because of your custom binary? Tnx!

Confirmed does **NOT** crash with 13.0 beta 2.

Confirmed **does** crash with nightly 20230106, newest I have downloaded, but I can try newer.

**Comment by andythenorth** [comment]
Backtrace of a related reproducible crash (missing squirrel `}` delimiter in this case).

`(lldb) run
Process 83099 launched: 'cabbage/OpenTTD.andythenorth/build/openttd' (arm64)
2023-01-29 21:04:41.602133+0000 openttd[83099:5459379] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x60000023c400> F8BB1C28-BAE8-11D6-9C31-00039315CD46
[2023-01-29 21:04:47] dbg: [script] [18] [S] Error /Users/andy2/Documents/OpenTTD/game/firs-gs/main.nut:291/10: expected '}'
[2023-01-29 21:04:47] dbg: [misc] [squirrel] Failed to compile '/Users/andy2/Documents/OpenTTD/game/firs-gs/main.nut'
[2023-01-29 21:04:47] dbg: [script] The script died unexpectedly.
Process 83099 stopped
* thread #10, name = 'ottd:game', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000100092608 openttd`ScriptInstance::LoadOnStack(std::__1::list<std::__1::variant<long long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long long, ScriptInstance::SQSaveLoadType>, std::__1::allocator<std::__1::variant<long long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long long, ScriptInstance::SQSaveLoadType> > >*) + 92
openttd`ScriptInstance::LoadOnStack:
->  0x100092608 <+92>:  ldr    x21, [x8]
    0x10009260c <+96>:  ldr    x22, [x20, #0x8]
    0x100092610 <+100>: strb   wzr, [sp]
    0x100092614 <+104>: mov    w8, #-0x1
Target 0: (openttd) stopped.
(lldb) bt
* thread #10, name = 'ottd:game', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000100092608 openttd`ScriptInstance::LoadOnStack(std::__1::list<std::__1::variant<long long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long long, ScriptInstance::SQSaveLoadType>, std::__1::allocator<std::__1::variant<long long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long long, ScriptInstance::SQSaveLoadType> > >*) + 92
    frame #1: 0x000000010014a0c0 openttd`Game::StartNew() + 368
    frame #2: 0x000000010036d148 openttd`AfterLoadGame() + 54380
    frame #3: 0x00000001003a97f8 openttd`DoLoad(LoadFilter*, bool) + 3348
    frame #4: 0x00000001003aa080 openttd`SaveOrLoad(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, SaveLoadOperation, DetailedFileType, Subdirectory, bool) + 1404
    frame #5: 0x00000001005b299c openttd`SafeLoad(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, SaveLoadOperation, DetailedFileType, GameMode, Subdirectory, LoadFilter*) + 212
    frame #6: 0x00000001005b31a4 openttd`SwitchToMode(SwitchMode) + 1468
    frame #7: 0x00000001005b6f64 openttd`GameLoop() + 472
    frame #8: 0x00000001003ed688 openttd`VideoDriver::GameLoop() + 116
    frame #9: 0x00000001003ed8a8 openttd`VideoDriver::GameThreadThunk(VideoDriver*) + 80
    frame #10: 0x00000001003ee180 openttd`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, bool StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::__1::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::'lambda'(char const*, void (*&&)(VideoDriver*), VideoDriver*&&), char const*, void (*)(VideoDriver*), VideoDriver*> >(void*) + 84
    frame #11: 0x00000001bc68026c libsystem_pthread.dylib`_pthread_start + 148
`

**Comment by andythenorth** [comment]
[Wruntown Transport, 01-01-1900.sav.zip](https://github.com/OpenTTD/OpenTTD/files/10530908/Wruntown.Transport.01-01-1900.sav.zip)
[firs-gs.zip](https://github.com/OpenTTD/OpenTTD/files/10530909/firs-gs.zip)
Save game attached - there's 1 unavailable grf (Iron Horse), can probably just ignore.

**Comment by andythenorth** [comment]
[iron-horse.grf.zip](https://github.com/OpenTTD/OpenTTD/files/10530910/iron-horse.grf.zip)

**Comment by glx22** [comment]
The attached save crashes on windows too.
```
>	openttd.exe!Squirrel::GetVM() Ligne 80	C++
 	openttd.exe!ScriptInstance::LoadOnStack(std::list<std::variant<__int64,std::string,unsigned __int64,enum ScriptInstance::SQSaveLoadType>,std::allocator<std::variant<__int64,std::string,unsigned __int64,enum ScriptInstance::SQSaveLoadType>>> * data) Ligne 696	C++
 	openttd.exe!Game::StartNew() Ligne 95	C++
 	openttd.exe!StartScripts() Ligne 551	C++
 	openttd.exe!AfterLoadGame() Ligne 3225	C++
 	openttd.exe!DoLoad(LoadFilter * reader, bool load_check) Ligne 3200	C++
 	openttd.exe!SaveOrLoad(const std::string & filename, SaveLoadOperation fop, DetailedFileType dft, Subdirectory sb, bool threaded) Ligne 3309	C++
 	openttd.exe!SafeLoad(const std::string & filename, SaveLoadOperation fop, DetailedFileType dft, GameMode newgm, Subdirectory subdir, LoadFilter * lf) Ligne 972	C++
 	openttd.exe!SwitchToMode(SwitchMode new_mode) Ligne 1069	C++
 	openttd.exe!GameLoop() Ligne 1475	C++
 	openttd.exe!VideoDriver::GameLoop() Ligne 37	C++
 	openttd.exe!VideoDriver::GameThread() Ligne 46	C++
 	openttd.exe!VideoDriver::GameThreadThunk(VideoDriver * drv) Ligne 82	C++
 	openttd.exe!StartNewThread::__l3::<lambda>(const char * name, void(*)(VideoDriver *) && F, VideoDriver * && <A_0>) Ligne 65	C++
 	[Code externe]	
 	openttd.exe!thread_start<unsigned int (__cdecl*)(void *),1>(void * const parameter) Ligne 97	C++
 	[Code externe]	
```

**Comment by JGRennison** [comment]
<details>
<summary>Bit more detail</summary>

```
/home/jgr/openttd/trunk/src/script/script_instance.cpp:696:38: runtime error: member call on null pointer of type 'struct Squirrel'
    #0 0x559b81c0beaf in ScriptInstance::LoadOnStack(std::__debug::list<std::variant<long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long long, ScriptInstance::SQSaveLoadType>, std::allocator<std::variant<long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long long, ScriptInstance::SQSaveLoadType> > >*) /home/jgr/openttd/trunk/src/script/script_instance.cpp:696
    #1 0x559b82098a6e in Game::StartNew() /home/jgr/openttd/trunk/src/game/game_core.cpp:94
    #2 0x559b82ded414 in StartScripts /home/jgr/openttd/trunk/src/saveload/afterload.cpp:548
    #3 0x559b82e443d1 in AfterLoadGame() /home/jgr/openttd/trunk/src/saveload/afterload.cpp:3219
    #4 0x559b83097011 in DoLoad /home/jgr/openttd/trunk/src/saveload/saveload.cpp:3200
    #5 0x559b8309817f in SaveOrLoad(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, SaveLoadOperation, DetailedFileType, Subdirectory, bool) /home/jgr/openttd/trunk/src/saveload/saveload.cpp:3309
    #6 0x559b8464edcb in SafeLoad(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, SaveLoadOperation, DetailedFileType, GameMode, Subdirectory, LoadFilter*) /home/jgr/openttd/trunk/src/openttd.cpp:972
    #7 0x559b8464f9f5 in SwitchToMode(SwitchMode) /home/jgr/openttd/trunk/src/openttd.cpp:1069
    #8 0x559b8465c55c in GameLoop() /home/jgr/openttd/trunk/src/openttd.cpp:1474
    #9 0x559b833bed8c in VideoDriver::GameLoop() /home/jgr/openttd/trunk/src/video/video_driver.cpp:37
    #10 0x559b833bf039 in VideoDriver::GameThread() /home/jgr/openttd/trunk/src/video/video_driver.cpp:44
    #11 0x559b833bf734 in VideoDriver::GameThreadThunk(VideoDriver*) /home/jgr/openttd/trunk/src/video/video_driver.cpp:81
    #12 0x559b833c5ba2 in StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}::operator()(char const*, void (*&&)(VideoDriver*), VideoDriver*&&) const /home/jgr/openttd/trunk/src/video/../thread.h:65
    #13 0x559b833c9b66 in void std::__invoke_impl<void, StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*>(std::__invoke_other, StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&&&)(VideoDriver*), VideoDriver*&&)#1}, char const*&&, void (*&&)(VideoDriver*), VideoDriver*&&) /usr/include/c++/9/bits/invoke.h:60
    #14 0x559b833c9724 in _ZSt8__invokeIZ14StartNewThreadIPFvP11VideoDriverEJS2_EEbPSt6threadPKcOT_DpOT0_EUlS8_OS4_OS2_E_JS8_S4_S2_EENSt15__invoke_resultIS9_JDpSB_EE4typeESA_SD_ /usr/include/c++/9/bits/invoke.h:95
    #15 0x559b833c9389 in void std::thread::_Invoker<std::tuple<StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*> >::_M_invoke<0ul, 1ul, 2ul, 3ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) /usr/include/c++/9/thread:244
    #16 0x559b833c90d6 in std::thread::_Invoker<std::tuple<StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*> >::operator()() /usr/include/c++/9/thread:251
    #17 0x559b833c908c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*> > >::_M_run() /usr/include/c++/9/thread:195
    #18 0x7f27edb0ede3  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6de3)
    #19 0x7f27edc28608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477
    #20 0x7f27ece7f132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132)

/home/jgr/openttd/trunk/src/script/api/../../script/squirrel.hpp:80:37: runtime error: member access within null pointer of type 'struct Squirrel'
    #0 0x559b817c5c10 in Squirrel::GetVM() /home/jgr/openttd/trunk/src/game/../script/squirrel.hpp:80
    #1 0x559b81c0beb7 in ScriptInstance::LoadOnStack(std::__debug::list<std::variant<long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long long, ScriptInstance::SQSaveLoadType>, std::allocator<std::variant<long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long long, ScriptInstance::SQSaveLoadType> > >*) /home/jgr/openttd/trunk/src/script/script_instance.cpp:696
    #2 0x559b82098a6e in Game::StartNew() /home/jgr/openttd/trunk/src/game/game_core.cpp:94
    #3 0x559b82ded414 in StartScripts /home/jgr/openttd/trunk/src/saveload/afterload.cpp:548
    #4 0x559b82e443d1 in AfterLoadGame() /home/jgr/openttd/trunk/src/saveload/afterload.cpp:3219
    #5 0x559b83097011 in DoLoad /home/jgr/openttd/trunk/src/saveload/saveload.cpp:3200
    #6 0x559b8309817f in SaveOrLoad(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, SaveLoadOperation, DetailedFileType, Subdirectory, bool) /home/jgr/openttd/trunk/src/saveload/saveload.cpp:3309
    #7 0x559b8464edcb in SafeLoad(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, SaveLoadOperation, DetailedFileType, GameMode, Subdirectory, LoadFilter*) /home/jgr/openttd/trunk/src/openttd.cpp:972
    #8 0x559b8464f9f5 in SwitchToMode(SwitchMode) /home/jgr/openttd/trunk/src/openttd.cpp:1069
    #9 0x559b8465c55c in GameLoop() /home/jgr/openttd/trunk/src/openttd.cpp:1474
    #10 0x559b833bed8c in VideoDriver::GameLoop() /home/jgr/openttd/trunk/src/video/video_driver.cpp:37
    #11 0x559b833bf039 in VideoDriver::GameThread() /home/jgr/openttd/trunk/src/video/video_driver.cpp:44
    #12 0x559b833bf734 in VideoDriver::GameThreadThunk(VideoDriver*) /home/jgr/openttd/trunk/src/video/video_driver.cpp:81
    #13 0x559b833c5ba2 in StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}::operator()(char const*, void (*&&)(VideoDriver*), VideoDriver*&&) const /home/jgr/openttd/trunk/src/video/../thread.h:65
    #14 0x559b833c9b66 in void std::__invoke_impl<void, StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*>(std::__invoke_other, StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&&&)(VideoDriver*), VideoDriver*&&)#1}, char const*&&, void (*&&)(VideoDriver*), VideoDriver*&&) /usr/include/c++/9/bits/invoke.h:60
    #15 0x559b833c9724 in _ZSt8__invokeIZ14StartNewThreadIPFvP11VideoDriverEJS2_EEbPSt6threadPKcOT_DpOT0_EUlS8_OS4_OS2_E_JS8_S4_S2_EENSt15__invoke_resultIS9_JDpSB_EE4typeESA_SD_ /usr/include/c++/9/bits/invoke.h:95
    #16 0x559b833c9389 in void std::thread::_Invoker<std::tuple<StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*> >::_M_invoke<0ul, 1ul, 2ul, 3ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) /usr/include/c++/9/thread:244
    #17 0x559b833c90d6 in std::thread::_Invoker<std::tuple<StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*> >::operator()() /usr/include/c++/9/thread:251
    #18 0x559b833c908c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*> > >::_M_run() /usr/include/c++/9/thread:195
    #19 0x7f27edb0ede3  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6de3)
    #20 0x7f27edc28608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477
    #21 0x7f27ece7f132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132)
```

</details>

**Comment by glx22** [comment]
So the issue is not the syntax error itself, but the data saved by the previous syntactically correct version of GS.

**Comment by andythenorth** [comment]
thanks :)
