### ISSUE TITLE
[Crash]: GetScrolledItemFromWidget assertion fails in autoreplace window when clicking right panel when left panel has no selected engine (is empty)

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#11326]
### Version of OpenTTD

master

### Steps to reproduce

1. Create a new game
2. Build a single locomotive
1. Open autoreplace window
3. Switch to wagon mode
4. Click the right panel
5. Assertion failure because vscroll[1] count does not match engines[1] size, due to vscroll[1] count not being reset when clearing engines[1] when no engine is selected.

### Upload crash files

Assertion: `this->GetCount() == container.size()`

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737275484928) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737275484928) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737275484928, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff6f9b476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff6f817f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff6f8171b in __assert_fail_base
    (fmt=0x7ffff7136150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5555560fea18 "this->GetCount() == container.size()", file=0x555556146250 "/home/jgr/openttd/trunk/src/widget_type.h", line=806, function=<optimised out>)
    at ./assert/assert.c:92
#6  0x00007ffff6f92e96 in __GI___assert_fail
    (assertion=0x5555560fea18 "this->GetCount() == container.size()", file=0x555556146250 "/home/jgr/openttd/trunk/src/widget_type.h", line=806, function=0x555556147880 "typename Tcontainer::iterator Scrollbar::GetScrolledItemFromWidget(Tcontainer&, int, const Window*, int, int, int) const [with Tcontainer = GUIList<GUIEngineListItem, unsigned char>; typename Tcontain"...) at ./assert/assert.c:101
#7  0x0000555555cc7330 in Scrollbar::GetScrolledItemFromWidget<GUIList<GUIEngineListItem, unsigned char> >(GUIList<GUIEngineListItem, unsigned char>&, int, Window const*, int, int, int) const
    (this=<optimised out>, container=..., clickpos=<optimised out>, w=0x5555566a81c0, widget=6, padding=0, line_height=-1) at /home/jgr/openttd/trunk/src/widget_type.h:806
#8  Scrollbar::GetScrolledItemFromWidget<GUIList<GUIEngineListItem, unsigned char> >(GUIList<GUIEngineListItem, unsigned char>&, int, Window const*, int, int, int) const
    (line_height=-1, padding=0, widget=6, w=0x5555566a81c0, clickpos=<optimised out>, container=..., this=<optimised out>) at /home/jgr/openttd/trunk/src/widget_type.h:804
#9  ReplaceVehicleWindow::OnClick(Point, int, int) (this=0x5555566a81c0, pt=..., widget=6, click_count=<optimised out>) at /home/jgr/openttd/trunk/src/autoreplace_gui.cpp:622
#10 0x00005555560d8969 in DispatchLeftClickEvent (click_count=1, y=55, x=<optimised out>, w=0x5555566a81c0) at /home/jgr/openttd/trunk/src/window.cpp:734
#11 MouseLoop (mousewheel=<optimised out>, click=<optimised out>) at /home/jgr/openttd/trunk/src/window.cpp:2850
#12 HandleMouseEvents() () at /home/jgr/openttd/trunk/src/window.cpp:2947
#13 0x0000555555c96725 in VideoDriver_SDL_Base::PollEvent() (this=0x5555566f36b0) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:417
#14 0x0000555555ca05c5 in VideoDriver::Tick() (this=this@entry=0x5555566f36b0) at /home/jgr/openttd/trunk/src/video/video_driver.cpp:135
#15 0x0000555555c9443e in VideoDriver_SDL_Base::LoopOnce() (this=0x5555566f36b0) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:627
#16 VideoDriver_SDL_Base::LoopOnce() (this=0x5555566f36b0) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:600
#17 VideoDriver_SDL_Base::MainLoop() (this=0x5555566f36b0) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:645
#18 0x0000555555efec3a in openttd_main(int, char**) (argc=<optimised out>, argv=<optimised out>) at /home/jgr/openttd/trunk/src/openttd.cpp:801
#19 0x00007ffff6f82d90 in __libc_start_call_main (main=main@entry=0x5555557c7940 <main(int, char**)>, argc=argc@entry=2, argv=argv@entry=0x7fffffffdb98) at ../sysdeps/nptl/libc_start_call_main.h:58
#20 0x00007ffff6f82e40 in __libc_start_main_impl (main=0x5555557c7940 <main(int, char**)>, argc=2, argv=0x7fffffffdb98, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffdb88)
    at ../csu/libc-start.c:392
#21 0x000055555586af35 in _start ()
```

**Comment by PeterN** [comment]
Hmm, the list is correct, the scroll bar count is not updated.
