### ISSUE TITLE
[Crash]: When using languages which uses SCC_GENDER_LIST

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#11521]
### Version of OpenTTD

master

### Steps to reproduce

Change the language to one which uses grammatical gender, e.g. German.

Look at a string which uses {G} string codes, e.g. in the order window using a go to nearest depot order (STR_ORDER_GO_TO_NEAREST_DEPOT_FORMAT).

The implementation of `StringParameters GetRemainingParameters(size_t offset)` looks like it ought to subtract offset from the length returned from `GetDataLeft()` ?

### Upload crash files

```
openttd: /home/jgr/openttd/trunk/src/core/span_type.hpp:101: constexpr span<T> span<T>::subspan(size_t, size_t) [with T = StringParameter; size_t = long unsigned int]: Assertion `offset + count <= size()' failed.

Thread 1 "openttd" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737275480832) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737275480832) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737275480832) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737275480832, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff6f9b476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff6f817f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff6f8171b in __assert_fail_base
    (fmt=0x7ffff7136150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555556198ae4 "offset + count <= size()", file=0x555556198348 "/home/jgr/openttd/trunk/src/core/span_type.hpp", line=101, function=<optimised out>)
    at ./assert/assert.c:92
#6  0x00007ffff6f92e96 in __GI___assert_fail
    (assertion=0x555556198ae4 "offset + count <= size()", file=0x555556198348 "/home/jgr/openttd/trunk/src/core/span_type.hpp", line=101, function=0x5555561982d8 "constexpr span<T> span<T>::subspan(size_t, size_t) [with T = StringParameter; size_t = long unsigned int]") at ./assert/assert.c:101
#7  0x00005555560005f5 in span<StringParameter>::subspan(unsigned long, unsigned long) (count=<optimised out>, offset=<optimised out>, this=<optimised out>) at /home/jgr/openttd/trunk/src/core/span_type.hpp:101
#8  0x0000555556008f24 in span<StringParameter>::subspan(unsigned long, unsigned long) (this=<optimised out>, this=<optimised out>, count=<optimised out>, offset=<optimised out>) at /home/jgr/openttd/trunk/src/core/pool_type.hpp:110
#9  StringParameters::GetRemainingParameters(unsigned long) (offset=<optimised out>, this=<optimised out>) at /home/jgr/openttd/trunk/src/strings_internal.h:132
#10 FormatString(StringBuilder&, char const*, StringParameters&, uint, bool, bool) (builder=..., str_arg=<optimised out>, args=..., case_index=0, game_script=false, dry_run=false) at /home/jgr/openttd/trunk/src/strings.cpp:1043
#11 0x0000555556004ebc in FormatString(StringBuilder&, char const*, StringParameters&, uint, bool, bool) (builder=..., str_arg=<optimised out>, args=..., case_index=0, game_script=false, dry_run=true)
    at /home/jgr/openttd/trunk/src/strings.cpp:1145
#12 0x0000555556004c89 in FormatString(StringBuilder&, char const*, StringParameters&, uint, bool, bool) (builder=..., str_arg=<optimised out>, args=..., case_index=0, game_script=false, dry_run=false)
    at /home/jgr/openttd/trunk/src/strings.cpp:898
#13 0x0000555556009a5b in GetStringWithArgs[abi:cxx11](unsigned int, StringParameters&) (args=..., string=<optimised out>) at /home/jgr/openttd/trunk/src/strings.cpp:344
#14 GetString[abi:cxx11](unsigned int) (string=string@entry=3433) at /home/jgr/openttd/trunk/src/strings.cpp:331
#15 0x0000555555da760a in DrawString(int, int, int, unsigned int, TextColour, StringAlignment, bool, FontSize)
    (left=37, right=540, top=17, str=str@entry=3433, colour=TC_BLACK, align=align@entry=SA_LEFT, underline=false, fontsize=FS_NORMAL) at /home/jgr/openttd/trunk/src/gfx.cpp:685
#16 0x0000555555f13b4e in DrawOrderString(Vehicle const*, Order const*, int, int, bool, bool, int, int, int)
    (v=<optimised out>, order=order@entry=0x555557828b70, order_index=order_index@entry=0, y=<optimised out>, selected=<optimised out>, timetable=timetable@entry=false, left=<optimised out>, middle=<optimised out>, right=540)
    at /home/jgr/openttd/trunk/src/order_gui.cpp:368
#17 0x0000555555f1756c in OrdersWindow::DrawWidget(Rect const&, int) const (this=0x5555576b0550, r=<optimised out>, widget=<optimised out>) at /home/jgr/openttd/trunk/src/order_gui.cpp:1130
#18 0x00005555560d01c0 in NWidgetBackground::Draw(Window const*) (this=0x5555577ce0c0, w=0x5555576b0550) at /home/jgr/openttd/trunk/src/widget.cpp:2388
#19 0x00005555560ce3cc in NWidgetContainer::Draw(Window const*) (this=0x5555582adf20, w=0x5555576b0550) at /home/jgr/openttd/trunk/src/widget.cpp:1362
#20 0x00005555560ce3cc in NWidgetContainer::Draw(Window const*) (this=0x5555576af770, w=0x5555576b0550) at /home/jgr/openttd/trunk/src/widget.cpp:1362
#21 0x00005555560ce4de in NWidgetStacked::Draw(Window const*) (this=0x55555713f6c0, w=<optimised out>) at /home/jgr/openttd/trunk/src/widget.cpp:1477
#22 0x00005555560ce3cc in NWidgetContainer::Draw(Window const*) (this=0x555557848860, w=0x5555576b0550) at /home/jgr/openttd/trunk/src/widget.cpp:1362
#23 0x00005555560d16a5 in Window::DrawWidgets() const (this=0x5555576b0550) at /home/jgr/openttd/trunk/src/widget.cpp:871
#24 0x00005555560d816b in DrawOverlappedWindowForAll(int, int, int, int) (left=left@entry=0, top=top@entry=169, right=right@entry=256, bottom=bottom@entry=304) at /home/jgr/openttd/trunk/src/window.cpp:935
#25 0x0000555555da24b0 in RedrawScreenRect(int, int, int, int) (left=0, top=169, right=256, bottom=304) at /home/jgr/openttd/trunk/src/gfx.cpp:1562
#26 0x0000555555da262e in DrawDirtyBlocks() () at /home/jgr/openttd/trunk/src/gfx.cpp:1637
#27 0x00005555560da7ff in UpdateWindows() () at /home/jgr/openttd/trunk/src/window.cpp:3078
#28 0x0000555555ca0ef5 in VideoDriver::Tick() (this=this@entry=0x5555566c7d60) at /home/jgr/openttd/trunk/src/video/video_driver.cpp:151
#29 0x0000555555c94d7e in VideoDriver_SDL_Base::LoopOnce() (this=0x5555566c7d60) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:627
#30 VideoDriver_SDL_Base::LoopOnce() (this=0x5555566c7d60) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:600
#31 VideoDriver_SDL_Base::MainLoop() (this=0x5555566c7d60) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:645
#32 0x0000555555f02098 in openttd_main(int, char**) (argc=<optimised out>, argv=<optimised out>) at /home/jgr/openttd/trunk/src/openttd.cpp:817
#33 0x00007ffff6f82d90 in __libc_start_call_main (main=main@entry=0x5555557c8fe0 <main(int, char**)>, argc=argc@entry=2, argv=argv@entry=0x7fffffffdba8) at ../sysdeps/nptl/libc_start_call_main.h:58
#34 0x00007ffff6f82e40 in __libc_start_main_impl (main=0x5555557c8fe0 <main(int, char**)>, argc=2, argv=0x7fffffffdba8, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffdb98)
    at ../csu/libc-start.c:392
#35 0x000055555586c085 in _start ()
```

**Comment by James103** [comment]
I was able to reproduce the crash in 96ec9c1b47f1691887c2493c49fbe3727b385158.
[crash20231130032547.zip](https://github.com/OpenTTD/OpenTTD/files/13508017/crash20231130032547.zip)
