### ISSUE TITLE
[Crash]: When using the sprite aligner window zoom buttons for zoom levels outside the min/max zoom settings

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#11618]
### Version of OpenTTD

Since #11518, 0434c1b474a45b56b9933778634b8bd64b2bf90f

### Steps to reproduce

1. Change the maximum zoom in setting in to 2x (instead of default 4x)
2. Open the sprite aligner window
3. Select a sprite
4. Click the 4x button

### Upload crash files

```
Thread 1 "openttd" received signal SIGSEGV, Segmentation fault.
Blitter_40bppAnim::Draw<(BlitterMode)0> (this=<optimised out>, bp=<optimised out>, zoom=<optimised out>) at /home/jgr/openttd/trunk/src/blitter/../gfx_type.h:193
193		Colour(uint data = 0) : data(data)
(gdb) bt
#0  Blitter_40bppAnim::Draw<(BlitterMode)0>(Blitter::BlitterParams const*, ZoomLevel) (this=<optimised out>, bp=<optimised out>, zoom=<optimised out>) at /home/jgr/openttd/trunk/src/blitter/../gfx_type.h:193
#1  0x0000555555daa80b in GfxBlitter<1, true>(Sprite const*, int, int, BlitterMode, SubSprite const*, SpriteID, ZoomLevel, DrawPixelInfo const*) (sprite=<optimised out>, x=<optimised out>, x@entry=111, y=<optimised out>, 
    y@entry=69, mode=mode@entry=BM_NORMAL, sub=sub@entry=0x0, sprite_id=<optimised out>, sprite_id@entry=0, zoom=ZOOM_LVL_BEGIN, dst=0x0) at /home/jgr/openttd/trunk/src/blitter/factory.hpp:140
#2  0x0000555555dab6f7 in GfxMainBlitter (zoom=ZOOM_LVL_BEGIN, sprite_id=0, sub=0x0, mode=BM_NORMAL, y=69, x=111, sprite=<optimised out>) at /home/jgr/openttd/trunk/src/gfx.cpp:1228
#3  DrawSprite(unsigned int, unsigned int, int, int, SubSprite const*, ZoomLevel) (img=<optimised out>, pal=pal@entry=0, x=x@entry=111, y=y@entry=69, sub=sub@entry=0x0, zoom=ZOOM_LVL_BEGIN) at /home/jgr/openttd/trunk/src/gfx.cpp:1024
#4  0x0000555555e99853 in SpriteAlignerWindow::DrawWidget(Rect const&, int) const (this=<optimised out>, r=<optimised out>, widget=<optimised out>) at /home/jgr/openttd/trunk/src/newgrf_debug_gui.cpp:918
#5  0x00005555560da608 in NWidgetBackground::Draw(Window const*) (this=0x55555784e670, w=0x555557460800) at /home/jgr/openttd/trunk/src/widget.cpp:2388
#6  0x00005555560d88fc in NWidgetContainer::Draw(Window const*) (this=0x5555578005c0, w=0x555557460800) at /home/jgr/openttd/trunk/src/widget.cpp:1359
#7  0x00005555560d88fc in NWidgetContainer::Draw(Window const*) (this=0x5555570d8320, w=0x555557460800) at /home/jgr/openttd/trunk/src/widget.cpp:1359
#8  0x00005555560d88fc in NWidgetContainer::Draw(Window const*) (this=0x555558401ee0, w=0x555557460800) at /home/jgr/openttd/trunk/src/widget.cpp:1359
#9  0x00005555560d88fc in NWidgetContainer::Draw(Window const*) (this=0x55555778c6e0, w=0x555557460800) at /home/jgr/openttd/trunk/src/widget.cpp:1359
#10 0x00005555560da18f in NWidgetBackground::Draw(Window const*) (this=0x5555577f1290, w=0x555557460800) at /home/jgr/openttd/trunk/src/widget.cpp:2389
#11 0x00005555560d88fc in NWidgetContainer::Draw(Window const*) (this=0x5555583ed0d0, w=0x555557460800) at /home/jgr/openttd/trunk/src/widget.cpp:1359
#12 0x00005555560d8a76 in NWidgetStacked::Draw(Window const*) (this=0x555557852600, w=<optimised out>) at /home/jgr/openttd/trunk/src/widget.cpp:1474
#13 0x00005555560d88fc in NWidgetContainer::Draw(Window const*) (this=0x5555583f06e0, w=0x555557460800) at /home/jgr/openttd/trunk/src/widget.cpp:1359
#14 0x00005555560dbbe5 in Window::DrawWidgets() const (this=0x555557460800) at /home/jgr/openttd/trunk/src/widget.cpp:872
#15 0x00005555560e258b in DrawOverlappedWindowForAll(int, int, int, int) (left=left@entry=0, top=top@entry=16, right=right@entry=448, bottom=bottom@entry=362) at /home/jgr/openttd/trunk/src/window.cpp:935
#16 0x0000555555da6080 in RedrawScreenRect(int, int, int, int) (left=0, top=16, right=448, bottom=362) at /home/jgr/openttd/trunk/src/gfx.cpp:1575
#17 0x0000555555da61fe in DrawDirtyBlocks() () at /home/jgr/openttd/trunk/src/gfx.cpp:1650
#18 0x00005555560e4c7f in UpdateWindows() () at /home/jgr/openttd/trunk/src/window.cpp:3082
#19 0x0000555555ca3ba5 in VideoDriver::Tick() (this=this@entry=0x5555566cdf70) at /home/jgr/openttd/trunk/src/video/video_driver.cpp:151
#20 0x0000555555c97a2e in VideoDriver_SDL_Base::LoopOnce() (this=0x5555566cdf70) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:627
#21 VideoDriver_SDL_Base::LoopOnce() (this=0x5555566cdf70) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:600
#22 VideoDriver_SDL_Base::MainLoop() (this=0x5555566cdf70) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:645
#23 0x0000555555f06f78 in openttd_main(int, char**) (argc=<optimised out>, argv=<optimised out>) at /home/jgr/openttd/trunk/src/openttd.cpp:817
#24 0x00007ffff6f82d90 in __libc_start_call_main (main=main@entry=0x5555557ca170 <main(int, char**)>, argc=argc@entry=2, argv=argv@entry=0x7fffffffdbc8) at ../sysdeps/nptl/libc_start_call_main.h:58
#25 0x00007ffff6f82e40 in __libc_start_main_impl (main=0x5555557ca170 <main(int, char**)>, argc=2, argv=0x7fffffffdbc8, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffdbb8)
    at ../csu/libc-start.c:392
#26 0x000055555586d705 in _start ()
```

**Comment by PeterN** [comment]
Nice, I forgot to consider those settings
