### ISSUE TITLE
Closing airport hanger window crashes the game

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#8724]
## Version of OpenTTD
master (2021-02-22)
Windows

## Expected result

No crash.

## Actual result

Crash. Assert, depot_map.h, line 55

## Steps to reproduce

- Start a game
- Build an airport
- Click hangar
- Close the hangar window

BOEM

I have no crashlog, as it fails creating it .. that might fully be my local setup :)

**Comment by LordAro** [comment]
```
0x00007fffe1e4d759 in RaiseException () from C:\WINDOWS\System32\KernelBase.dll
(gdb) bt
#0  0x00007fffe1e4d759 in RaiseException () from C:\WINDOWS\System32\KernelBase.dll
#1  0x00007ff685ed7e9d in CustomAbort (signal=22) at C:/msys64/home/LordAro/OpenTTD/src/os/windows/crashlog_win.cpp:603
#2  0x00007fffe23fadfb in raise () from C:\WINDOWS\System32\msvcrt.dll
#3  0x00007fffe23fda29 in msvcrt!_wassert () from C:\WINDOWS\System32\msvcrt.dll
#4  0x00007ff685f78826 in GetDepotIndex (t=33416) at C:/msys64/home/LordAro/OpenTTD/src/depot_map.h:55
#5  0x00007ff686235d97 in DepotWindow::~DepotWindow (this=0x15d66be8510, __in_chrg=<optimized out>) at C:/msys64/home/LordAro/OpenTTD/src/depot_gui.cpp:297
#6  0x00007ff686235d35 in DepotWindow::~DepotWindow (this=0x15d66be8510, __in_chrg=<optimized out>) at C:/msys64/home/LordAro/OpenTTD/src/depot_gui.cpp:299
#7  0x00007ff686185384 in DispatchLeftClickEvent (w=0x15d66be8510, x=0, y=7, click_count=1) at C:/msys64/home/LordAro/OpenTTD/src/window.cpp:710
#8  0x00007ff68618b09f in MouseLoop (click=MC_LEFT, mousewheel=0) at C:/msys64/home/LordAro/OpenTTD/src/window.cpp:2961
#9  0x00007ff68618b4f6 in HandleMouseEvents () at C:/msys64/home/LordAro/OpenTTD/src/window.cpp:3058
#10 0x00007ff685f389b6 in WndProcGdi (hwnd=0x141034, msg=513, wParam=1, lParam=1966080) at C:/msys64/home/LordAro/OpenTTD/src/video/win32_v.cpp:656
#11 0x00007fffe376e858 in USER32!CallWindowProcW () from C:\WINDOWS\System32\user32.dll
#12 0x00007fffe376e299 in USER32!DispatchMessageW () from C:\WINDOWS\System32\user32.dll
#13 0x00007ff685f39f43 in VideoDriver_Win32::MainLoop (this=0x15d6557c560) at C:/msys64/home/LordAro/OpenTTD/src/video/win32_v.cpp:1202
#14 0x00007ff686059205 in openttd_main (argc=3, argv=0x2f895ff9f0) at C:/msys64/home/LordAro/OpenTTD/src/openttd.cpp:851
#15 0x00007ff685ede0a6 in WinMain (hInstance=0x7ff685e00000, hPrevInstance=0x0, lpCmdLine=0x15d63c243e3 "-g -G0", nCmdShow=10) at C:/msys64/home/LordAro/OpenTTD/src/os/windows/win32.cpp:446
#16 0x00007ff68657ba72 in main (flags=<optimized out>, cmdline=<optimized out>, inst=<optimized out>) at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18
#17 0x00007ff685e013c1 in __tmainCRTStartup () at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:321
#18 0x00007ff685e014d6 in WinMainCRTStartup () at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:176
```

https://github.com/OpenTTD/OpenTTD/blob/80fb1c74f04be7a571f6a721d2f6d82ed95de9b6/src/depot_gui.cpp#L297

Oops.
