### ISSUE TITLE
[Bug]: MSAN fails to run settingsgen

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#9949]
### Version of OpenTTD

12

### Expected result

Being able to run strgen with [MSAN](https://clang.llvm.org/docs/MemorySanitizer.html) enabled

### Actual result

```
==28658==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x4b15d6 in std::ostreambuf_iterator<char, std::char_traits<char> >::ostreambuf_iterator(std::ostream&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/streambuf_iterator.h:274:17
    #1 0x4b15d6 in StrMakeValid(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, StringValidationSettings) /home/micro/projects/OpenTTD/OpenTTD/src/string.cpp:305:33
    #2 0x4ace17 in IniGroup::IniGroup(IniLoadFile*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/micro/projects/OpenTTD/OpenTTD/src/ini_load.cpp:53:15
    #3 0x4ae5ce in IniLoadFile::LoadFromDisk(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Subdirectory) /home/micro/projects/OpenTTD/OpenTTD/src/ini_load.cpp:268:16
    #4 0x4a71c4 in LoadIniFile(char const*) /home/micro/projects/OpenTTD/OpenTTD/src/settingsgen/settingsgen.cpp:207:7
    #5 0x4a71c4 in ProcessIniFile(char const*) /home/micro/projects/OpenTTD/OpenTTD/src/settingsgen/settingsgen.cpp:443:26
    #6 0x4a71c4 in main /home/micro/projects/OpenTTD/OpenTTD/src/settingsgen/settingsgen.cpp:503:40
    #7 0x7f8bfab90d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #8 0x7f8bfab90e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #9 0x4259a4 in _start (/home/micro/projects/OpenTTD/OpenTTD/build-fuzz-msan/src/settingsgen/settingsgen+0x4259a4)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/streambuf_iterator.h:274:17 in std::ostreambuf_iterator<char, std::char_traits<char> >::ostreambuf_iterator(std::ostream&)
```

### Steps to reproduce

Compile OpenTTD with `-fsanitize=memory` on clang. It will crash before really starting on `settingsgen`.

**Comment by LordAro** [comment]
Probably a false positive due to libstdc++ being "uninstrumented" - https://clang.llvm.org/docs/MemorySanitizer.html#handling-external-code

Seems like the "easiest" solution is to build libc++ (rather than libstdc++) with MSAN enabled and link against that instead

**Comment by TrueBrain** [comment]
Hmm, you make sense. :p

@frosch123 found out that if we compile only OpenTTD with MSAN, it will fail on ICU .. so running MSAN will require a lot of custom compiling.

I am going to close this issues .. it is not realistic to make a build setup for MSAN for both these reasons.

 Tnx for looking into this :)
